sonar.projectKey=revisium_revisium-payment-client
sonar.organization=revisium

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/__tests__**,**/__mocks__**,**/*.spec.ts,src/generated/**
sonar.coverage.exclusions=**/__tests__**,**/__mocks__**,**/*.spec.ts,src/generated/**

sonar.issue.ignore.multicriteria=ci1,ci2

sonar.issue.ignore.multicriteria.ci1.ruleKey=githubactions:S6505
sonar.issue.ignore.multicriteria.ci1.resourceKey=**/.github/workflows/ci.yml

sonar.issue.ignore.multicriteria.ci2.ruleKey=githubactions:S6505
sonar.issue.ignore.multicriteria.ci2.resourceKey=**/.github/workflows/npm-publish.yml
